#!/usr/bin/env python3
# Ainara AI Companion Framework Project
# Copyright (C) 2025 Rubén Gómez - khromalabs.org
#
# This file is dual-licensed under:
# 1. GNU Lesser General Public License v3.0 (LGPL-3.0)
#    (See the included LICENSE_LGPL3.txt file or look into
#    <https://www.gnu.org/licenses/lgpl-3.0.html> for details)
# 2. Commercial license
#    (Contact: rgomez@khromalabs.org for licensing options)
#
# You may use, distribute and modify this code under the terms of either license.
# This notice must be preserved in all copies or substantial portions of the code.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.

"""Start the Ainara Sentinel Scheduler automatically at logon. Opt-in, reversible.

    --status    (default) is it installed, and is the scheduler running now?
    --install   register the logon task
    --remove    unregister it

Why this exists: the scheduler supervises the trading executor daemon and the
position watchdog, restarting either if it dies. Started by hand it does that
perfectly — until the machine reboots, at which point nothing restarts IT and an open
hedge sits unguarded with no indication that anything is missing. If you hold
positions across a reboot, this is the gap.

It does NOT arm the strategy. The scheduler brings services up and runs whatever crons
you have already enabled in scheduler.yaml; "the engine is up" and "the strategy is
armed" stay separate switches. Nothing here places an order.

USER-LEVEL only: the task runs as you, at your logon, with limited privileges. No
admin rights, no SYSTEM account, no service install. Remove it any time with
--remove, or from Task Scheduler by name.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TASK_NAME = "Ainara Sentinel Scheduler"


def _config_dir():
    """Where the launcher script is written — beside ainara.yaml."""
    cfg = os.environ.get("AINARA_CONFIG")
    if cfg:
        return Path(cfg).parent
    if os.name == "nt":
        return Path(os.environ.get("APPDATA", Path.home())) / "ainara"
    return Path(os.environ.get("XDG_CONFIG_HOME",
                               Path.home() / ".config")) / "ainara"


def _venv_python():
    sub = ("Scripts", "python.exe") if os.name == "nt" else ("bin", "python")
    p = PROJECT_ROOT / "venv" / sub[0] / sub[1]
    return p if p.exists() else Path(sys.executable)


def _log_dir():
    """Prefer the configured logging.directory so autostart logs land with the rest."""
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from ainara.framework.config import ConfigManager
        d = ConfigManager().get("logging.directory")
        if d:
            Path(d).mkdir(parents=True, exist_ok=True)
            return Path(d)
    except Exception:
        pass
    return _config_dir() / "Logs"


def _launcher_path():
    return _config_dir() / ("ainara-autostart.ps1" if os.name == "nt"
                            else "ainara-autostart.sh")


def write_launcher():
    """Write the small script the task invokes.

    A launcher rather than a raw command line for two reasons: the scheduler prints
    its supervision log to stdout, which needs redirecting to a file to be any use at
    logon, and a file on disk is something you can read to see exactly what will run.
    """
    log_dir = _log_dir()
    py, sched = _venv_python(), PROJECT_ROOT / "scripts" / "scheduler.py"
    path = _launcher_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        body = f"""# Generated by scripts/autostart.py — safe to inspect, edit or delete.
# Launches the Ainara Sentinel Scheduler detached, with its log captured.
# The scheduler holds a PID-file lock, so a duplicate launch aborts harmlessly.
Start-Process -FilePath "{py}" `
  -ArgumentList '-u','{sched}','--quiet' `
  -WorkingDirectory "{PROJECT_ROOT}" `
  -WindowStyle Hidden `
  -RedirectStandardOutput "{log_dir / 'scheduler.log'}" `
  -RedirectStandardError  "{log_dir / 'scheduler.err.log'}"
"""
    else:
        body = f"""#!/bin/sh
# Generated by scripts/autostart.py — safe to inspect, edit or delete.
cd "{PROJECT_ROOT}" || exit 1
exec "{py}" -u "{sched}" --quiet \\
  >> "{log_dir / 'scheduler.log'}" 2>> "{log_dir / 'scheduler.err.log'}"
"""
    path.write_text(body, encoding="utf-8")
    if os.name != "nt":
        path.chmod(0o755)
    return path


def _schtasks(*args):
    return subprocess.run(["schtasks", *args], capture_output=True, text=True)


def _powershell(script):
    return subprocess.run(
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script],
        capture_output=True, text=True)


def _register_via_powershell(launcher):
    """Register the logon task through the ScheduledTasks module.

    `schtasks /sc onlogon` fails with "Access is denied" for a normal user: that
    trigger is machine-scoped, so it wants elevation. Register-ScheduledTask with the
    trigger bound to a SPECIFIC user is per-user and succeeds unelevated — which
    matters, because requiring admin to protect your own positions is a good way to
    ensure nobody turns this on.
    """
    ps = f"""
$act = New-ScheduledTaskAction -Execute 'powershell.exe' `
  -Argument '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{launcher}"'
$trg = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\\$env:USERNAME"
$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries -StartWhenAvailable
Register-ScheduledTask -TaskName '{TASK_NAME}' -Action $act -Trigger $trg `
  -Settings $set -Force -ErrorAction Stop | Out-Null
"""
    return _powershell(ps)


def status():
    installed = None
    if os.name == "nt":
        r = _schtasks("/query", "/tn", TASK_NAME)
        installed = r.returncode == 0
        print(f"logon task '{TASK_NAME}': "
              f"{'INSTALLED' if installed else 'not installed'}")
    else:
        print("logon autostart: not managed on this platform (see --install output)")
    launcher = _launcher_path()
    print(f"launcher script : {launcher}"
          f"{'' if launcher.exists() else '  (absent)'}")
    print(f"scheduler log   : {_log_dir() / 'scheduler.log'}")

    # Is it up right now? Independent of whether autostart is installed.
    try:
        import psutil
        running = [p.info["pid"] for p in psutil.process_iter(["pid", "cmdline"])
                   if p.info["cmdline"] and "scheduler.py" in " ".join(p.info["cmdline"])]
        print(f"scheduler now   : {'running, pid ' + str(running[0]) if running else 'NOT RUNNING'}")
    except Exception:
        print("scheduler now   : (install psutil to check)")
    return 0 if installed else 1


def install():
    launcher = write_launcher()
    print(f"launcher written: {launcher}")
    if os.name != "nt":
        print("\nThis platform is not wired up. Equivalent systemd user unit:\n")
        print(f"""  # ~/.config/systemd/user/ainara-scheduler.service
  [Unit]
  Description=Ainara Sentinel Scheduler
  [Service]
  ExecStart={launcher}
  Restart=on-failure
  [Install]
  WantedBy=default.target

  systemctl --user enable --now ainara-scheduler
  loginctl enable-linger $USER   # so it survives logout""")
        return 0

    # -WindowStyle Hidden keeps it off-screen; ExecutionPolicy Bypass applies to THIS
    # invocation only and does not change the machine policy.
    action = ('powershell.exe -NoProfile -ExecutionPolicy Bypass '
              f'-WindowStyle Hidden -File "{launcher}"')
    r = _register_via_powershell(launcher)
    if r.returncode != 0:
        # Fall back to schtasks, which reports a clearer error when something other
        # than the trigger scope is wrong.
        alt = _schtasks("/create", "/tn", TASK_NAME, "/tr", action,
                        "/sc", "onlogon", "/rl", "limited", "/f")
        if alt.returncode != 0:
            print("FAILED to register the task:")
            print((r.stderr or r.stdout).strip()[:400])
            print("\nAdd it by hand in Task Scheduler instead:")
            print("  trigger: at log on (this user)")
            print(f"  action : {action}")
            return 1
    print(f"registered logon task: {TASK_NAME}")
    print("  runs as you, limited privileges, at every logon")
    print("  it does NOT arm the strategy — only brings services up")
    print(f"\nRemove any time:  python {Path(__file__).name} --remove")
    return 0


def remove():
    if os.name != "nt":
        print("Not managed on this platform. Disable the systemd unit:")
        print("  systemctl --user disable --now ainara-scheduler")
        return 0
    r = _schtasks("/delete", "/tn", TASK_NAME, "/f")
    if r.returncode != 0:
        # Same asymmetry as install: a task registered per-user may need the module.
        alt = _powershell(
            f"Unregister-ScheduledTask -TaskName '{TASK_NAME}'"
            " -Confirm:$false -ErrorAction Stop")
        if alt.returncode != 0:
            print((r.stderr or r.stdout).strip()[:300])
            return 1
    print(f"removed logon task: {TASK_NAME}")
    launcher = _launcher_path()
    if launcher.exists():
        print(f"launcher left in place (harmless, delete if you like): {launcher}")
    print("Anything already running is untouched — this only stops it starting"
          " automatically next time.")
    return 0


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    g = p.add_mutually_exclusive_group()
    g.add_argument("--install", action="store_true", help="register the logon task")
    g.add_argument("--remove", action="store_true", help="unregister it")
    g.add_argument("--status", action="store_true", help="show state (default)")
    a = p.parse_args()
    sys.exit(install() if a.install else remove() if a.remove else status())
