#!/bin/sh
rep="/tmp/ainara_code_report.txt"
cd `git root`
for i in `find . -name "*.yaml" -or -name "*.py" -or -name "*.js" -or -name "*.spec" | grep -vE "^./build|^./node_modules|^./venv|^./dist|^./site"`; do wc -l $i; done > $rep
cat $rep
echo "TOTAL:"
awk '{sum += $1} END {print sum}' $rep
