name: Testing Release Build

on:
  push:
    #    branches: [ testing ]
    tags: [ 'testing-*' ]
    #  pull_request:
    #    branches: [ testing ]

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [macos-latest, macos-latest-arm64, windows-latest]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # Add permissions block here for the job
    permissions:
      contents: write
      packages: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }} # Checkout the specific tag that triggered the workflow
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Updated to Python 3.12

    - name: Create virtual environment
      shell: bash
      run: |
        python -m venv venv
        if [ "${{ runner.os }}" == "Windows" ]; then
          source venv/Scripts/activate
        else
          source venv/bin/activate
        fi
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: Verify Python version
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          source venv/Scripts/activate
          venv/Scripts/python.exe --version
        else
          source venv/bin/activate
          python --version  # Verify correct Python version
        fi

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          source venv/scripts/activate
          venv/Scripts/python.exe -m pip install --upgrade pip
          venv/Scripts/python.exe -m pip install -r requirements.txt
        else
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: Install project in editable mode
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          source venv/scripts/activate
          venv/Scripts/python.exe -m pip install -e .
        else
          source venv/bin/activate
          pip install -e .
        fi

    - name: Show location and files
      shell: bash
      run: |
        pwd
        ls

    - name: Run build script
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          source venv/scripts/activate
        else
          source venv/bin/activate
        fi
        chmod +x bin/build
        bin/build --skip-npm-build --skip-git-tag

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Matches Electron and other dependencies version requirements

    - name: Install npm dependencies
      shell: bash
      run: |
        npm install

    - name: Build frontend for ${{ matrix.os }}
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          npm run build:linux
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          npm run build:mac
        else
          npm run build:win
        fi

    - name: Determine Archive Name
      id: archive_name
      shell: bash
      run: |
        # Extract tag name (e.g., testing-v1.0.0)
        TAG_NAME="${{ github.ref_name }}"
        # Extract branch part (e.g., testing)
        BRANCH_PART="${TAG_NAME%-v*}"
        # Extract version part (e.g., v1.0.0)
        VERSION_PART="${TAG_NAME#*-}"
        # Clean the OS name (e.g., macos-latest -> macos, macos-14 -> macos)
        OS_NAME="$(echo "${{ matrix.os }}" | sed 's/-latest$//' | sed 's/-[0-9]*$//')"

        # Determine architecture suffix
        ARCH_SUFFIX=""
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          ARCH_SUFFIX="-${{ runner.arch }}"
        fi

        # Construct the desired filename
        echo "ARCHIVE_FILENAME=ainara-polaris-${BRANCH_PART}-${VERSION_PART}-${OS_NAME}${ARCH_SUFFIX}.zip" >> $GITHUB_ENV
        echo "Generated filename: ainara-polaris-${BRANCH_PART}-${VERSION_PART}-${OS_NAME}${ARCH_SUFFIX}.zip"

    - name: Create Archive (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Remove-Item -Path dist/servers -Recurse -Force
        # Windows uses latest.yml
        if (Test-Path "latest.yml") {
            Copy-Item "latest.yml" -Destination dist\
        }
        Compress-Archive -Path dist\* -DestinationPath ${{ env.ARCHIVE_FILENAME }}

    - name: Create YAML Metadata for ZIP (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $zipPath = "${{ env.ARCHIVE_FILENAME }}"
        $zipSize = (Get-Item $zipPath).Length
        $sha512 = (Get-FileHash -Path $zipPath -Algorithm SHA512).Hash
        $yamlContent = "version: 0.3.0`nfiles:`n  - url: ${{ env.ARCHIVE_FILENAME }}`n    sha512: $sha512`n    size: $zipSize`npath: ${{ env.ARCHIVE_FILENAME }}`nsha512: $sha512`nreleaseDate: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss.fffZ')"
        Set-Content -Path "latest.yml" -Value $yamlContent
        Copy-Item "latest.yml" -Destination "${{ env.ARCHIVE_FILENAME }}.yml"

    - name: Create Archive (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        rm -rf dist/servers
        # macOS uses latest-mac.yml, Linux uses latest-linux.yml
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          [ -f "latest-mac.yml" ] && cp latest-mac.yml dist/
        else
          [ -f "latest-linux.yml" ] && cp latest-linux.yml dist/
        fi
        zip -s 2g -r ${{ env.ARCHIVE_FILENAME }} dist/

    - name: Create YAML Metadata for ZIP (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        zip_path="${{ env.ARCHIVE_FILENAME }}"
        zip_size=$(stat -f %z "$zip_path")
        sha512=$(shasum -a 512 "$zip_path" | awk '{print $1}')
        ARCHIVE_FILENAME="${{ env.ARCHIVE_FILENAME }}"
        RELEASE_DATE=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')
        echo "version: 0.3.0" > "latest-mac.yml"
        echo "files:" >> "latest-mac.yml"
        echo "  - url: $ARCHIVE_FILENAME" >> "latest-mac.yml"
        echo "    sha512: $sha512" >> "latest-mac.yml"
        echo "    size: $zip_size" >> "latest-mac.yml"
        echo "path: $ARCHIVE_FILENAME" >> "latest-mac.yml"
        echo "sha512: $sha512" >> "latest-mac.yml"
        echo "releaseDate: $RELEASE_DATE" >> "latest-mac.yml"
        cp "latest-mac.yml" "${{ env.ARCHIVE_FILENAME }}.yml"

    - name: Package testing artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_FILENAME }}
        path: ${{ env.ARCHIVE_FILENAME }}
        if-no-files-found: error


    - name: Create testing release
      # Only run this step if the workflow was triggered by a tag push
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Testing Release
        body: |
          Automated testing release from testing branch
          OS: ${{ matrix.os }}
          Python: 3.12
          SHA: ${{ github.sha }}
        draft: false
        prerelease: true
        files: |
          ${{ env.ARCHIVE_FILENAME }}
          ${{ env.ARCHIVE_FILENAME }}.yml
