name: Testing Release Build

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: testing  # Explicitly checkout testing branch

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Updated to Python 3.12

    - name: Create virtual environment
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: Verify Python version
      shell: bash
      run: |
        source venv/bin/activate
        python --version  # Verify correct Python version

    - name: Install dependencies
      shell: bash
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build script
      shell: bash
      run: |
        source venv/bin/activate
        chmod +x bin/build
        bin/build

    - name: Package testing artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-testing-servers
        path: |
          dist/orakle
          dist/pybridge
        if-no-files-found: error

    - name: Create testing release
      if: github.ref == 'refs/heads/testing'
      uses: softprops/action-gh-release@v1
      with:
        tag: testing-${{ github.sha }}
        name: Testing Release
        body: |
          Automated testing release from testing branch
          OS: ${{ matrix.os }}
          Python: 3.12
          SHA: ${{ github.sha }}
        draft: true
        prerelease: true
        files: |
          dist/orakle/**
          dist/pybridge/**

